global using BookingCinema525.DataAccess;
global using BookingCinema525.Models;
//global using BookingCinema525.DataAccess;
global using Microsoft.AspNetCore.Mvc;
global using BookingCinema525.ViewModels;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using BookingCinema525_new.Utilities;
global using BookingCinema525_new.ViewModels;
global using BookingCinema525_new.Models;